#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  liftLimitSwitch, sensorTouch)
#pragma config(Sensor, I2C_1,  leftShooterIEM, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  rightShooterIEM, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           shooterMotorL, tmotorVex393_MC29, PIDControl, encoderPort, I2C_1)
#pragma config(Motor,  port3,           shooterMotorR, tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           liftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool buffer;
bool shooterOn;

void shooterToggle(bool button) {
	if(button && buffer) {
		shooterOn = !shooterOn;
		buffer = false;
	}
	else if(!button && !buffer) {
		buffer = true;
	}

motor[shooterMotorL] = shooterOn ? 100: 0;
motor[shooterMotorR] = shooterOn ? 100: 0;
}

bool liftCanRun;
bool ableToStop;

void liftWithLimitSwitch(bool button, bool switchPressed) {
	if(button) {
		if(!switchPressed) {
			ableToStop = true;
		}
		else if(switchPressed && ableToStop) {
			liftCanRun = false;
			ableToStop = false;
		}

		if(liftCanRun) {
			motor[liftMotor] = 100;
		}
		else {
			motor[liftMotor] = 0;
		}
	}
	else {
		liftCanRun = true;
		motor[liftMotor] = 0;
	}
}

task main()
{
	nMotorPIDSpeedCtrl[shooterMotorL] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[shooterMotorR] = mtrSpeedReg;

	while(1 == 1) {
		shooterToggle(vexRT[Btn6U]);
		liftWithLimitSwitch(vexRT[Btn5U], SensorValue(liftLimitSwitch));
	}
}
